[package]
name = "recollectd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.librecollect]
path = "../librecollect"
version = "0.1.0"

[dependencies]
dirs = "4.0"
clap = { version = "3.2", features = ["derive"] }
anyhow = "1.0"
chrono = "0.4"
log = "0.4"
pretty_env_logger = "0.4"
serde_json = "1"