[package]
name = "librecollect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cron = "0.11"
thiserror = "1.0"
notify-rust = "4"